version: '3'

services:
  cat-classifier-tfserving:
    image: emacski/tensorflow-serving:2.4.1-linux_arm_armv7-a_neon_vfpv4
    environment: 
        - MODEL_NAME=cat_classifier
    volumes:
        - /home/pi/intellicatflap_sandbox/models/cat_classifier_v0_tobivscatflap/saved_model:/models/cat_classifier/1/
    restart: always

  cat-classifier-client:
    image: catclassifierclient:v1
    build:
      context: ./client
    volumes:
        - /Users/administrator/private/intellicatflap_sandbox:/app/data